apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-app
  labels:
    app: fake-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-app
  template:
    metadata:
      labels:
        app: fake-app
    spec:
      containers:
        - name: fake-app
          image: marcoldp/fakeapp:v0.0.2
          ports:
            - containerPort: 8080