apiVersion: apps/v1 #kubernetes api version
kind: Deployment #specifies the kubernetes obj/resource
metadata: #data that helps specify unique information about the object
  name: fake-app
  labels:
    app: fake-app
spec: 
  replicas: 1 # how many pods to create
  selector: # defines which pods should be managed by the deployment
    matchLabels:
      app: fake-app
  template: # describes all instructions executed in the pod
    metadata:
      labels:
        app: fake-app
    spec: # contains the actual description of the Pods contents
      containers:
        - name: fake-app
          image: fakeapp:v0.0.1
          ports:
            - containerPort: 8080